export const Colors = {
  primary: '#004953',
  primaryLight: '#004953',
  primaryDark: '#222222', //BLACK TO LIGHT
  secondary: '#fe7062', //RED VERY LIGHT
  secondaryLight: '#2b2e4a', //NAVY BLUE
  secondaryDark: '#004953', //RED - Palette
  backgroundLight: '#fcfcfc', //WHITE TO GRAY
  backgroundDark: '#2C2C2C', //BALCK TO GREY
  textPrimaryLight: '#222222', //BLACK LIGHT
  textPrimaryDark: '#fcfcfc', //WHITE TO GRAY
  textSecondaryLight: '#2C2C2C', //BALCK TO GREY
  textSecondaryDark: '#d4d6d5', //GRAY,
  textPlaceholder: '#939393',
  red: '#c50c0c',
  lava: '#DCDCDC',
  grey: '#C4C4C4',
  grey_light: '#f5f6fb',
  black: '#2c2c2c',
  white: 'white',
  accent: '#17545b',
  green: 'rgba(193,241,209,0.65)',
  green2: '#039a83',
  green3: '#27AE60',
  green_light: '#2A8754',
  light: '#EEEEEE',
  dark: '#333',
  background: '#ededed',
  lightRed: '#ff4f7e',
  darkRed: '#d9365e',
  purple: '#8f06e4',
  skyBlue: 'skyblue',
  yellow: '#FAA61B',
  lightyellow: 'rgba(255,224,142,0.73)',
  pink: '#ff4c98',
  gold: '#B49C56',
  line: '#282C35',
  gray: '#CCCCCC',
  darkGray: '#999999',
  orange: '#ffa500',
  blue: '',

  darkOverlayColor: 'rgba(0, 0, 0, 0.4)',
  darkOverlayColor2: 'rgba(0, 0, 0, 0.8)',
  lightOverlayColor: 'rgba(255, 255, 255, 0.6)',
  primaryAlpha: 'rgba(99, 122, 255, 0.15)',
  redAlpha: 'rgba(255, 84, 84, 0.15)',
  greenAlpha: 'rgba(96, 197, 168, 0.15)',
  purpleAlpha: 'rgba(146, 6, 228, 0.15)',

  // bags background colors
  bag1Bg: '#ea7a72',
  bag2Bg: '#c2c5d1',
  bag3Bg: '#82a7c9',
  bag4Bg: '#d49d8f',
  bag5Bg: '#ccd9c6',
  bag6Bg: '#767676',
  bag7Bg: '#d1c8c3',
  bag8Bg: '#dca47f',
  bag9Bg: '#eb849c',
  bag10Bg: '#979dc1',
  bag11Bg: '#c7d3c0',
};

export const darkTheme = {
  mode: 'dark',
  PRIMARY_BACKGROUND_COLOR: Colors.backgroundDark,
  SECONDARY_BACKGROUND_COLOR: Colors.yellow,
  PRIMARY_TEXT_COLOR: Colors.textPrimaryDark,
  PRIMARY_TEXTINPUTITEM_COLOR: Colors.textPrimaryDark,
  SECONDARY_TEXT_COLOR: Colors.textSecondaryDark,
  PRIMARY_BUTTON_COLOR: Colors.secondaryDark,
  PRIMARY_BUTTON_TEXT_COLOR: Colors.textPrimaryDark,
  STATUS_BAR_STYLE: Colors.backgroundDark,
  BOTTOM_TAB_BACKGROUND: Colors.primaryDark,
  BOTTOM_TAB_ICON_COLOR: Colors.gray,
  BOTTOM_TAB_ICON_BACK: Colors.backgroundDark,
  BOTTOM_TAB_TEXT: Colors.white,
  LIST_ITEM_COLOR: Colors.primaryDark,
  CAROUSEL_ITEM_COLOR: Colors.primaryDark,
  INPUT_ITEM_COLOR: Colors.primaryDark,
  PRIMARY_BACKGROUNDPROFILE_COLOR: Colors.darkGray,
  PRIMARY_BACKGROUNDPROFILEFILD_COLOR: Colors.darkGray,
  TOGGLE_TITLE: Colors.white,
  TOGGLE_ACTIVE_TITLE: Colors.backgroundDark,
  BIO_DETAILS_ITEMS_BACKGROUND: Colors.dark,
  PRIMARY_DARK: Colors.textPlaceholder,
  TEXT_PRIMARY_DARK: Colors.textPrimaryLight,
};

export const lightTheme = {
  mode: 'light',
  PRIMARY_BACKGROUND_COLOR: Colors.backgroundLight,
  SECONDARY_BACKGROUND_COLOR: Colors.yellow,
  PRIMARY_TEXT_COLOR: Colors.textPrimaryLight,
  PRIMARY_TEXTINPUTITEM_COLOR: Colors.grey,
  SECONDARY_TEXT_COLOR: Colors.textSecondaryLight,
  PRIMARY_BUTTON_COLOR: Colors.secondaryLight,
  PRIMARY_BUTTON_TEXT_COLOR: Colors.textPrimaryDark,
  STATUS_BAR_STYLE: Colors.backgroundLight,
  BOTTOM_TAB_BACKGROUND: Colors.white,
  BOTTOM_TAB_ICON_COLOR: Colors.gray,
  BOTTOM_TAB_ICON_BACK: Colors.primaryLight,
  BOTTOM_TAB_TEXT: Colors.primaryLight,
  LIST_ITEM_COLOR: Colors.grey_light,
  CAROUSEL_ITEM_COLOR: Colors.background,
  INPUT_ITEM_COLOR: Colors.grey,
  PRIMARY_BACKGROUNDPROFILE_COLOR: Colors.backgroundLight,
  PRIMARY_BACKGROUNDPROFILEFILD_COLOR: Colors.textPrimaryLight,
  TOGGLE_TITLE: Colors.darkGray,
  TOGGLE_ACTIVE_TITLE: Colors.backgroundDark,
  BIO_DETAILS_ITEMS_BACKGROUND: Colors.grey,
  PRIMARY_DARK: Colors.textSecondaryDark,
  TEXT_PRIMARY_DARK: Colors.backgroundLight,
};
